AWSTemplateFormatVersion: "2010-09-09"
Description: Launch EC2 instance with user-defined parameters

Parameters:
  AMIId:
    Description: Enter the Amazon Machine Image (AMI) ID for the EC2 instance.
    Type: String
    Default: ami-0f34c5ae932e6f0e4 # By default Amazon Linux 2 AMI is used. Replace with your desired value

  InstanceType:
    Description: Choose the EC2 instance type (e.g., t2.micro, m5.large).
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
      # Add more instance types as needed
    Default: t2.micro

  VpcId:
    Description: Enter the VPC ID where the instance will be launched.
    Type: AWS::EC2::VPC::Id

  KeyName:
    Description: Enter the EC2 Key Pair name for SSH access.
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup
      ImageId: !Ref AMIId

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access from a specific IP address
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: <your_public_ip>/32  # Replace with your desired IP address range

Outputs:
  InstanceId:
    Description: Instance ID of the launched EC2 instance.
    Value: !Ref MyEC2Instance

  PublicIPAddress:
    Description: Public IP address of the EC2 instance.
    Value: !GetAtt MyEC2Instance.PublicIp
