name: AWS GitHub OIDC connection example workflow
on:
  push:
    branches:
      - main
    paths:
      - 'aws-cookbook/cdk/github-oidc/**'
env:
  AWS_REGION : "us-east-1"
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::951043241862:role/github-actions-deployment-role
          aws-region: us-east-1
      - name:  List S3 Objects
        run: |
          aws s3 ls s3://my-demo-github-oidc-bucket/images/ --region us-east-1